version: '3.7'

services:
  # MongoDB
  cadmus-renovella-mongo:
    image: mongo
    container_name: cadmus-renovella-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017
    networks:
      - cadmus-renovella-network

  # PostgreSQL
  cadmus-renovella-pgsql:
    image: postgres
    container_name: cadmus-renovella-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-renovella-network
    # volumes:
      #- pgsql-vol:/var/lib/postgresql/data

  # Cadmus Renovella API
  cadmus-renovella-api:
    image: vedph2020/cadmus-renovella-api:4.0.4
    ports:
      - 40392:80
    depends_on:
      - cadmus-renovella-mongo
      - cadmus-renovella-pgsql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-renovella-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-renovella-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-renovella-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__INDEXDELAY=25
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
    networks:
      - cadmus-renovella-network

networks:
  cadmus-renovella-network:
    driver: bridge

#volumes:
#  pgsql-vol:
